batch_size: 32
epochs: 200
exp_name: lanro_d2_mmvae
labels:
beta: 1
lr: 1e-3
mixing: moe
iterseeds: 1
n_latents: 32
obj: dreg
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 10
test_split: 0.1
dataset_name: lanro
modality_1:
  decoder: TxtTransformer
  encoder: TxtTransformer
  prior: normal
  recon_loss: gaussian_nll
  mod_type: language
  growtype: neurons
  path: ./data/lanro/D2/lanro_instructions.pkl
  test_datapath:
modality_2:
  decoder: Transformer
  encoder: Transformer
  recon_loss: gaussian_nll
  mod_type: actions
  prior: normal
  growtype: neurons
  path: ./data/lanro/D2/lanro_actions.pkl
  test_datapath:
modality_3:
  decoder: CNN
  encoder: RESCNN
  recon_loss: gaussian_nll
  prior: normal
  mod_type: front RGB
  growtype: neurons
  path: ./data/lanro/D2/lanro_images.pkl
  test_datapath:
